"""
calibration_model.py — AI Calibration Layer
============================================
A learning-based layer that reconciles discrepancies between geometric
surface curvature and anatomical keypoint-based estimates.

This module implements Step 6 from the research roadmap:
  "A learning-based calibration layer is introduced to reconcile discrepancies
   between geometric surface curvature and anatomical keypoint-based estimates."

Supports:
  - RandomForest baseline (scikit-learn)
  - MLP deep calibration (PyTorch)
  - Feature engineering from both pipelines
  - Dataset integration (Mendeley + SpineTrack + Own)
"""

import os
import numpy as np
import pandas as pd
import joblib
import warnings
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
import config

warnings.filterwarnings("ignore")

# ────────────────────────────────────────────────────────────────────
# FEATURE ENGINEERING
# ────────────────────────────────────────────────────────────────────

def build_feature_matrix(anatomical_results: dict,
                         geometric_results: dict) -> pd.DataFrame:
    """
    Construct the feature matrix X from both pipeline outputs.

    Features (matching on time axis via nearest-frame alignment):
      spinepose_angle     — smoothed Cobb angle from SpinePose
      surface_curvature   — smoothed geometric curvature
      angle_diff          — spinepose_angle - surface_curvature
      trunk_lean          — global lean bias removed in FIX-2
      confidence          — mean SpinePose keypoint confidence
      curvature_variance  — rolling variance of geometric curvature (stability)

    Target:
      spinepose_angle_smoothed — used as the gold-standard reference
    """
    # Align time series (anatomical is the reference)
    anat_t = np.array(anatomical_results["time"])
    geo_t  = np.array(geometric_results["time"])
    geo_cv = np.array(geometric_results["curvature_s"])

    # Nearest-neighbour alignment
    aligned_geo = []
    for t in anat_t:
        idx = int(np.argmin(np.abs(geo_t - t)))
        aligned_geo.append(float(geo_cv[idx]) if idx < len(geo_cv) else np.nan)
    aligned_geo = np.array(aligned_geo)

    spine_angle = np.array(anatomical_results["kyphosis"])
    lean        = np.array(anatomical_results["lean_bias"])
    conf        = np.array(anatomical_results["confidence"])

    # Rolling variance (window = 5) as a stability feature
    curv_var = pd.Series(aligned_geo).rolling(5, min_periods=1).var().values

    df = pd.DataFrame({
        "spinepose_angle":        spine_angle,
        "surface_curvature":      aligned_geo,
        "angle_diff":             spine_angle - aligned_geo,
        "trunk_lean":             lean,
        "confidence":             conf,
        "curvature_variance":     curv_var,
        "spinepose_angle_smoothed": spine_angle,   # target = same (per-video)
    })

    df.dropna(inplace=True)
    return df


def load_dataset_csv(dataset_label: str = "own") -> pd.DataFrame:
    """
    Load pre-built feature CSVs from the merged dataset.
    Expected columns: all CALIBRATION_CONFIG['features'] + target column.

    The own_dataset/features.csv is generated by running unified_pipeline.py
    on the collected video dataset.
    """
    path = os.path.join(config.DATASET_DIR, dataset_label, "features.csv")
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Dataset CSV not found: {path}\n"
            f"Run unified_pipeline.py --build-dataset first."
        )
    return pd.read_csv(path)


# ────────────────────────────────────────────────────────────────────
# RANDOM FOREST CALIBRATION MODEL
# ────────────────────────────────────────────────────────────────────

class RandomForestCalibrator:
    """
    Baseline calibration model using RandomForest regression.

    Learns: (spinepose, geometric, diff, lean, conf, variance) -> corrected angle
    """

    def __init__(self):
        cfg = config.CALIBRATION_CONFIG
        self.model    = RandomForestRegressor(
            n_estimators=cfg["n_estimators"],
            random_state=cfg["random_state"],
            n_jobs=-1,
        )
        self.scaler    = StandardScaler()
        self.features  = cfg["features"]
        self.target    = cfg["target"]
        self.trained   = False
        self.metrics   = {}

    def fit(self, df: pd.DataFrame):
        """Train the calibrator on feature DataFrame."""
        X = df[self.features].values
        y = df[self.target].values

        X_train, X_test, y_train, y_test = train_test_split(
            X, y,
            test_size=config.CALIBRATION_CONFIG["test_size"],
            random_state=config.CALIBRATION_CONFIG["random_state"],
        )

        X_train_s = self.scaler.fit_transform(X_train)
        X_test_s  = self.scaler.transform(X_test)

        self.model.fit(X_train_s, y_train)
        y_pred = self.model.predict(X_test_s)

        self.metrics = {
            "MAE":         float(mean_absolute_error(y_test, y_pred)),
            "STD_residual":float(np.std(y_test - y_pred)),
            "R":           float(np.corrcoef(y_test, y_pred)[0, 1]),
            "n_train":     len(X_train),
            "n_test":      len(X_test),
        }
        self.trained = True
        self._print_metrics()
        return self

    def predict(self, df: pd.DataFrame) -> np.ndarray:
        """Return corrected angle predictions."""
        if not self.trained:
            raise RuntimeError("Model not trained. Call .fit() first.")
        X = self.scaler.transform(df[self.features].values)
        return self.model.predict(X)

    def feature_importance(self) -> dict:
        """Return feature importance dict."""
        if not self.trained:
            return {}
        return dict(zip(self.features, self.model.feature_importances_))

    def save(self, label: str = "rf_calibrator"):
        path = os.path.join(config.MODEL_DIR, f"{label}.joblib")
        joblib.dump({"model": self.model, "scaler": self.scaler}, path)
        print(f"  Model saved -> {path}")

    def load(self, label: str = "rf_calibrator"):
        path = os.path.join(config.MODEL_DIR, f"{label}.joblib")
        obj  = joblib.load(path)
        self.model   = obj["model"]
        self.scaler  = obj["scaler"]
        self.trained = True
        return self

    def _print_metrics(self):
        m = self.metrics
        print(f"\n  [RandomForest Calibrator] Evaluation:")
        print(f"    MAE:             {m['MAE']:.3f} deg")
        print(f"    STD (residuals): {m['STD_residual']:.3f} deg")
        print(f"    Correlation R:   {m['R']:.4f}")
        print(f"    Train / Test:    {m['n_train']} / {m['n_test']} samples")


# ────────────────────────────────────────────────────────────────────
# MLP DEEP CALIBRATION MODEL (PyTorch)
# ────────────────────────────────────────────────────────────────────

try:
    import torch
    import torch.nn as nn
    from torch.utils.data import DataLoader, TensorDataset
    TORCH_AVAILABLE = True
except ImportError:
    TORCH_AVAILABLE = False


class _MLPNet(nn.Module if TORCH_AVAILABLE else object):
    """Small MLP: 6 features -> 64 -> 32 -> 1."""
    def __init__(self, in_features: int = 6):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_features, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 1),
        )

    def forward(self, x):
        return self.net(x).squeeze(1)


class MLPCalibrator:
    """
    Deep calibration model (PyTorch MLP).
    Requires PyTorch. Falls back to RandomForestCalibrator if unavailable.
    """

    def __init__(self, epochs: int = 100, lr: float = 1e-3, batch_size: int = 32):
        if not TORCH_AVAILABLE:
            raise ImportError("PyTorch not installed. Use RandomForestCalibrator instead.")
        self.epochs     = epochs
        self.lr         = lr
        self.batch_size = batch_size
        self.scaler     = StandardScaler()
        self.features   = config.CALIBRATION_CONFIG["features"]
        self.target     = config.CALIBRATION_CONFIG["target"]
        self.model      = None
        self.metrics    = {}

    def fit(self, df: pd.DataFrame):
        X = df[self.features].values.astype(np.float32)
        y = df[self.target].values.astype(np.float32)

        X_train, X_test, y_train, y_test = train_test_split(
            X, y,
            test_size=config.CALIBRATION_CONFIG["test_size"],
            random_state=config.CALIBRATION_CONFIG["random_state"],
        )
        X_train = self.scaler.fit_transform(X_train).astype(np.float32)
        X_test  = self.scaler.transform(X_test).astype(np.float32)

        self.model = _MLPNet(in_features=X_train.shape[1])
        optimizer  = torch.optim.Adam(self.model.parameters(), lr=self.lr)
        loss_fn    = nn.MSELoss()

        ds     = TensorDataset(torch.tensor(X_train), torch.tensor(y_train))
        loader = DataLoader(ds, batch_size=self.batch_size, shuffle=True)

        self.model.train()
        for epoch in range(self.epochs):
            for xb, yb in loader:
                optimizer.zero_grad()
                loss = loss_fn(self.model(xb), yb)
                loss.backward()
                optimizer.step()
            if (epoch + 1) % 20 == 0:
                print(f"    Epoch {epoch+1}/{self.epochs}  loss={loss.item():.4f}")

        # Evaluation
        self.model.eval()
        with torch.no_grad():
            y_pred = self.model(torch.tensor(X_test)).numpy()
        self.metrics = {
            "MAE":          float(mean_absolute_error(y_test, y_pred)),
            "STD_residual": float(np.std(y_test - y_pred)),
            "R":            float(np.corrcoef(y_test, y_pred)[0, 1]),
        }
        print(f"\n  [MLP Calibrator] MAE={self.metrics['MAE']:.3f}  "
              f"R={self.metrics['R']:.4f}")
        return self

    def predict(self, df: pd.DataFrame) -> np.ndarray:
        X = torch.tensor(
            self.scaler.transform(df[self.features].values).astype(np.float32)
        )
        self.model.eval()
        with torch.no_grad():
            return self.model(X).numpy()

    def save(self, label: str = "mlp_calibrator"):
        path = os.path.join(config.MODEL_DIR, f"{label}.pt")
        torch.save(self.model.state_dict(), path)
        joblib.dump(self.scaler, os.path.join(config.MODEL_DIR, f"{label}_scaler.joblib"))
        print(f"  MLP saved -> {path}")


# ────────────────────────────────────────────────────────────────────
# DATASET UTILITIES (Mendeley + SpineTrack + Own)
# ────────────────────────────────────────────────────────────────────

def load_mendeley_ranges() -> dict:
    """
    Load clinical Cobb angle ranges from the Mendeley Posture Dataset.
    Used for: (a) defining normal/mild/severe thresholds,
              (b) validating SpinePose output against literature.

    If the CSV is unavailable, falls back to config.CLINICAL_RANGES.
    """
    csv_path = os.path.join(config.MENDELEY_DATASET_PATH, "posture_ranges.csv")
    if not os.path.exists(csv_path):
        print("  [Mendeley] CSV not found — using config.CLINICAL_RANGES defaults.")
        return config.CLINICAL_RANGES
    df = pd.read_csv(csv_path)
    ranges = {}
    for _, row in df.iterrows():
        ranges[row["condition"]] = (float(row["min_deg"]), float(row["max_deg"]))
    return ranges


def load_spinetrack_keypoints(split: str = "train") -> pd.DataFrame | None:
    """
    Load SpineTrack keypoint annotations.
    Used for improving keypoint detection and testing pipeline structure.
    split: 'train' | 'val' | 'test'
    """
    path = os.path.join(config.SPINETRACK_DATASET_PATH, f"{split}_keypoints.csv")
    if not os.path.exists(path):
        print(f"  [SpineTrack] {split} split not found at {path}")
        return None
    return pd.read_csv(path)


def load_own_dataset_labels() -> pd.DataFrame | None:
    """
    Load labels for the own collected dataset.
    Expected CSV columns: filename, label (normal/mild/severe)
    """
    if not os.path.exists(config.OWN_LABELS_CSV):
        print(f"  [OwnDataset] Labels CSV not found: {config.OWN_LABELS_CSV}")
        return None
    df = pd.read_csv(config.OWN_LABELS_CSV)
    print(f"  [OwnDataset] Loaded {len(df)} labeled samples.")
    return df


def validate_against_clinical_ranges(predictions: np.ndarray,
                                      method: str = "anatomical") -> dict:
    """
    Compare predicted angles against Mendeley-derived clinical ranges.
    Returns proportion of predictions in each clinical category.
    """
    ranges = config.CLINICAL_RANGES.get(
        "kyphosis" if method == "anatomical" else "geometric",
        config.CLINICAL_RANGES["kyphosis"]
    )
    n      = len(predictions)
    result = {}
    for cat, (lo, hi) in ranges.items():
        pct = float(np.sum((predictions >= lo) & (predictions < hi)) / n * 100)
        result[cat] = pct
        print(f"    {cat}: {pct:.1f}% of frames")
    return result


if __name__ == "__main__":
    print("Calibration module ready.")
    print(f"PyTorch available: {TORCH_AVAILABLE}")
    print(f"Features: {config.CALIBRATION_CONFIG['features']}")
